apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplewebapp
spec:
  template:
    spec:
      containers:
      - name: samplewebapp
        env:
        - name: ENVIRONMENT
          value: dev
