
patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: 633834615594.dkr.ecr.us-west-2.amazonaws.com/samplewebapp
  newName: 633834615594.dkr.ecr.us-west-2.amazonaws.com/samplewebapp
  newTag: 27da5feac832f046e417dc48ff39ec3657ff43e2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: staging-
